### ISSUE TITLE
Stream Deck Connect App availability

### ISSUE THREAD

**Issue by mbentin** [elgatosf/streamdeck-kit-ipad#41]
I want to test that on a real device, but the Stream Deck Connect App is unavailable in my region (Germany, France). Would it be possible to make it available?

**Comment by r-dent** [comment]
Hi @mbentin !
We hope to release it to the public during this week. Until then, you should be able to install it via this TestFlight link: [testflight.apple.com/join/U4bWfk8O](https://testflight.apple.com/join/U4bWfk8O).
