### ISSUE TITLE
Readme Example Issue

### ISSUE THREAD

**Issue by blakekrone** [elgatosf/streamdeck-kit-ipad#47]
Under the previews section, the readme has been updated to reflect the following:

Previews

You can use Simulator in XCode Previews.

#Preview {
    StreamDeckSimulator.PreviewView(streamDeck: .mini) {
        MyStreamDeckLayout()
    }
}

Shouldn't it be as reflected in the docs page as the following:

#Preview("Stream Deck +") {
    StreamDeckSimulator.PreviewView(streamDeck: .plus) { device in
        device.render(MyStreamDeckLayout)
    }
}

**Comment by r-dent** [comment]
Hey @blakekrone !

Good catch! You are absolutely right. That must have been slipped through during a early refactoring. We will address this as soon as possible.
Thanks for pointing it out! 👍 

Best, Roman.
